cargo-features = ["profile-rustflags"]

[package]
name = "gba-rt"
version = "0.1.0"
authors = [""]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agb = "0.21.1"
fixed = "1.28.0"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
strip = "symbols"
opt-level = 3
codegen-units = 1
panic = "abort"
lto = "fat"
incremental = true
rustflags = ["-Z", "location-detail=none"]
debug=true

[profile.release.package."*"]
strip = "symbols"
opt-level = 3
codegen-units = 1
incremental = true
rustflags = ["-Z", "location-detail=none"]
debug=true
