[package]
name = "GBA_RTX"
version = "0.0.1"
authors = [""]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agb = "0.15.0"
agb_fixnum = "0.15.0"
fixed = "2.0.0-alpha.11"

[profile.dev]
opt-level = 3
debug = true
overflow-checks = false

[profile.release]
opt-level = 3
lto = "fat"
debug = true
codegen-units = 1
overflow-checks = false
